### ISSUE TITLE
A Typo in Content Management Page

### ISSUE THREAD

**Issue by 0065paula** [Prototypr/gftw-project#2]
> In a 'headless CMS' setup, the front-end is completely separated from the back end, ao there are 2 parts of the Prototypr app, both in different GitHub Repos:

I think the 'ao' is supposed to be 'so'?

**Comment by GraemeFulton** [comment]
Thank you for pointing it out!
The instructions are a first version from when the site was put together. It's a good reference but there are gaps in the instructions. Needs editing and tidying up!
